# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!


target 'FlixBusDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MaterialActivityIndicator'

  # Pods for FlixBusDemo

  target 'FlixBusDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixBusDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
